### PR TITLE
Add back Capable.xcodeproj for Carthage support.

### PR DESCRIPTION
**Pull request by jefflen**
> Please fill out all lines starting with a 📝 when filing a pull request to give us an idea of what you did. 

## Issue information
📝This resolved issue #47 for not having Carthage support in version `1.1.1`.

## Goal
📝Re-supporting Carthage

## Implementation
📝Re-introducing the `Capable.xcodeproj` file

## Testing
📝Tested on Carthage which worked.

### CODE REVIEW

**Comment by chrs1885** [comment]
@jefflen First and foremost thank you for your contribution. While the changes totally fix the issue, I had to get rid of the framework project file to support the cocoapods lib template. I think we can also solve the problem by marking the Capable schemes as shared inside the example workspace. Could you try to open the workspace, and select „manage schemes“ next to the „build and run“ button. If I remember correctly, there should be checkboxes for sharing individual schemes. This should be enough to readd carthage support. 🥳

**Comment by jefflen** [comment]
@chrs1885 The problem I found was that there is no Capable framework target in the Example workspace to be shared, also I find that the example workspace probably is not the best place for placing the scheme. That was why I only reintroduced the `Capable.xcodeproj` in the root level. 

I am not familiar with the Cocoapods lib templates but I have moved `Capable.xcodeproj` to a dedicated folder, could yo please let me know if this will help for the support?

If you still think it's better to have the target and scheme inside the `Example.xcworkspace`, I can also try it with adding all the source files to `Example.xcodeproj`.

**Comment by chrs1885** [comment]
@jefflen Can you review & test #49 ? It might be an alternative solution to support Carthage again :)

**Comment by jefflen** [comment]
As this was fixed in #49, close it now.

**Pull request closed without merging**
