### PR TITLE
Add Carthage support by sharing Pod schemes

### PR DESCRIPTION
**Pull request by chrs1885**
## Issue information
Alternative to #48 #47 by sharing schemes of the Pods-project.

## Goal
Adding Carthage support without explicitly re-adding the Capable project file.

## Implementation
Sharing the shemes.

### CODE REVIEW

**Comment by jefflen** [comment]
@chrs1885 First of all sorry for the late reply. Happy New Year!

Thanks for suggesting the alternative solution, however I have tried to install by using Carthage, it wouldn't compile due to this error:

```
/usr/bin/xcrun xcodebuild -workspace /Users/hlu/git_tree/pulse-ios/Carthage/Checkouts/Capable/Example/Example.xcworkspace -scheme Capable-iOS -configuration Release -derivedDataPath /Users/hlu/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2_11B52/Capable/1a932fba4037527b140be9aa605cd5e0ebbd5f31 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/27/t2yd_x8n0fdb9ggvg4nh6tmw8z8bsn/T/Capable SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/hlu/git_tree/pulse-ios/Carthage/Checkouts/Capable)User defaults from command line:
    IDEArchivePathOverride = /var/folders/27/t2yd_x8n0fdb9ggvg4nh6tmw8z8bsn/T/Capable
    IDEDerivedDataPathOverride = /Users/hlu/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2_11B52/Capable/1a932fba4037527b140be9aa605cd5e0ebbd5f31

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos13.2
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

note: Using new build system
note: Planning build
note: Constructing build description
error: /Users/hlu/git_tree/pulse-ios/Carthage/Checkouts/Capable/Example/Pods/Target Support Files/Capable-iOS/Capable-iOS.xcconfig: unable to open file (in target "Capable-iOS" in project "Pods") (in target 'Capable-iOS' from project 'Pods')
error: /Users/hlu/git_tree/pulse-ios/Carthage/Checkouts/Capable/Example/Pods/Target Support Files/Capable-iOS/Capable-iOS.xcconfig: unable to open file (in target "Capable-iOS" in project "Pods") (in target 'Capable-iOS' from project 'Pods')
error: /Users/hlu/git_tree/pulse-ios/Carthage/Checkouts/Capable/Example/Pods/Target Support Files/Capable-iOS/Capable-iOS.xcconfig: unable to open file (in target "Capable-iOS" in project "Pods") (in target 'Capable-iOS' from project 'Pods')
error: missing module map file: '/Users/hlu/git_tree/pulse-ios/Carthage/Checkouts/Capable/Example/Pods/Target Support Files/Capable-iOS/Capable-iOS.modulemap (in target 'Capable-iOS' from project 'Pods')

** ARCHIVE FAILED **
```

I think the problem is the installed Pods folder wasn't pushed, hence it couldn't be compiled. One solution is to push the installed Pods to the repo. But I'm not sure if it makes sense.

I have also made some changes in #48 to include `Capable.xcodeproj` into the `Example.xcworkspace`, could you help to have a look and see if it makes more sense?

**Comment by chrs1885** [comment]
Hi @jefflen. Happy new year to you, too. An thanks for being so patient =)
I do prefer pushing the example app's Pods dir over re-adding the project file. Can you give it another shot?
Simply add `github "chrs1885/Capable" "feature/48-carthage-support"`to your Cartfile.

**Comment by jefflen** [comment]
Hi @chrs1885, sorry for the delay of response as I just came back from a one month long vacation. 

I have tried adding it in Carthage with the branch `feature/48-carthage-support` and it works perfectly fine! I will close my PR now.

I am looking forward this to be released soon and I can skip to add the branch name in my `Cartfile`.

Thanks a lot for your support.

**Comment by chrs1885** [comment]
@jefflen Thank you so much for your support during the last couple of weeks. Finally, Carthage support has been fixed in https://github.com/chrs1885/Capable/tree/1.1.2 🍺

**Pull request merged**
